language: ruby

rvm:
- 2.0.0

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -f d spec/

notifications:
  email: false
