language: ruby
rvm:
- 2.0.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -f d spec/
before_deploy:
- gem install heroku
deploy:
  provider: heroku
  api_key:
    secure: "coGLeX7eLYPzlZGFy4ByOH6xi+TffBENj0jrIPr3Olgf47y7pf5R3Hla5ziXV8jyni5FFzMYAC1sZ5RkMX9Ybzeoq7aw2hTOrHSM5W+czF8vqM0Xqh7DRy82iN2DikykTnt9CcpeGW0Zy2lQ32aUSW7h+mypJwvj6xdfqpAaX3Y="
  app: ratebeer-wadror
  run: rake db:migrate
notifications:
  email: false